#!/bin/bash
BASEDIR=$(pwd);

# Disable basic AOSP packages
cd $BASEDIR/build;
git apply $BASEDIR/patches/build.diff;

# Disable basic LineageOS packages
cd $BASEDIR/vendor/lineage;
git apply $BASEDIR/patches/vendor_lineage.diff;
