#!/bin/bash
cd build;
git apply ../patches/build.diff;
cd ../device/motorola/lux;
git apply ../../../patches/device_motorola_lux.diff;
cd ../msm8916-common;
git apply ../../../patches/device_motorola_msm8916-common.diff;
cd ../../../frameworks/base;
git apply ../../patches/frameworks_base.diff;
cd ../../vendor/cm;
git apply ../../patches/vendor_cm.diff;
cd ../motorola;
git apply ../../patches/vendor_motorola.diff;
