#!/bin/bash
BASEDIR=$(pwd);

# Disable basic AOSP packages
cd $BASEDIR/build;
git apply $BASEDIR/patches/build.diff;

# Device patches
cd $BASEDIR/device/xiaomi/daisy;
git apply $BASEDIR/patches/device_xiaomi_daisy.diff;

# Disable basic LineageOS packages
cd $BASEDIR/vendor/lineage;
git apply $BASEDIR/patches/vendor_lineage.diff;

# microG signature spoofing patch
cd $BASEDIR/frameworks/base;
git apply $BASEDIR/patches/frameworks_base.diff
